---
title: "R Notebook"
output: html_notebook
---

https://www.tutorialspoint.com/r/r_arrays.htm


```{r}
# Create two vectors of different lengths.
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)

# Take these vectors as input to the array.
result <- array(c(vector1, vector2), dim = c(3,3,2))
print(result)
```

```{r}
# Create two vectors of different lengths.
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)

column.names <- c("COL1","COL2","COL3")
row.names    <- c("ROW1","ROW2","ROW3")
matrix.names <- c("Matrix1","Matrix2")

# Take these vectors as input to the array.
result <- array(c(vector1, vector2), dim = c(3,3,2), 
                dimnames = list(row.names, 
                                column.names, 
                                matrix.names))
print(result)
```

## Accessing Array Elements
```{r}
# Create two vectors of different lengths.
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)
column.names <- c("COL1","COL2","COL3")
row.names    <- c("ROW1","ROW2","ROW3")
matrix.names <- c("Matrix1","Matrix2")

# Take these vectors as input to the array.
result <- array(c(vector1,vector2), dim = c(3,3,2), 
                dimnames = list(row.names, 
                                column.names, 
                                matrix.names))
print(result)
# Print the third row of the second matrix of the array.
print(result[3,,2])

# Print the element in the 1st row and 3rd column of the 1st matrix.
print(result[1,3,1])

# Print the 2nd Matrix.
print(result[,,2])
```


```{r}
# print all matrices
# sapply(result, function(x) {x = seq(1, dim(result)[3])
#                                 result[,,x]})

for (i in 1:dim(result)[3])
    print(result[,,i])
```


```{r}
# Create two vectors of different lengths.
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)

# Take these vectors as input to the array.
array1 <- array(c(vector1,vector2),dim = c(3,3,2))

# Create two vectors of different lengths.
vector3 <- c(9,1,0)
vector4 <- c(6,0,11,3,14,1,2,6,9)

array2 <- array(c(vector1, vector2), dim = c(3,3,2))

# create matrices from these arrays.
matrix1 <- array1[,,2]
matrix2 <- array2[,,2]

# Add the matrices.
result <- matrix1+matrix2
print(result)
```

## Calculations Across Array Elements

    apply(x, margin, fun)
    
    `x` is an array.

    `margin` is the name of the data set used.

    `fun` is the function to be applied across the elements of the array.
    

```{r}
# Create two vectors of different lengths.
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)

# Take these vectors as input to the array.
new.array <- array(c(vector1,vector2), dim = c(3,3,2))
print(new.array)

# Use apply to calculate the sum of the rows across all the matrices.
result <- apply(new.array, c(1), sum)
print(result)
```


```{r}
# array[rows, columns, dimensions] # Syntax to access columns, rows and dimensions in arrays with more than two dimensions.
x <- array(1:250, dim=c(10,5,5)); 

x[2:5, 3,] # Example to generate 10x5x5 array and how to retrieve slices from all sub-arrays.
```



```{r}
Z <- array(1:12, dim=c(12,8)); X <- array(12:1, dim=c(12,8)) # Creates arrays Z and X with same dimensions.

calarray <- Z/X # Divides Z/X elements and assigns result to array 'calarray'.

# t(my_array) # Transposes 'my_array'; a more flexible transpose function is 'aperm(my_array, perm)'.
```

