---
title: "R Notebook"
output: html_notebook
---

```{r}
conv3d <- function(A, B) {
    if (is.matrix(A) & is.matrix(B)) {
        A <- array(A, dim = c(dim(A), 1))
        B <- array(B, dim = c(dim(B), 1))
    }
    D <- array(0, dim = c(2*dim(A)[1]-1, 2*dim(A)[2]-1, 2*dim(A)[3]-1))
    
    for (i in 1:dim(A)[3]) {  # 1, 2, 3
        D[,,i] <- i *.O$convn(A[,,i], B[,,i])
    }
    
    if (dim(A)[3] > 1) {
        for (j in (dim(A)[3]-1):1) {   # 2, 1
            D[,,i+(dim(A)[3]-j)] <- j *.O$convn(A[,,j], B[,,j])
        }
    }
    D   
}


# C = ones(5, 4, 3)
# conv3d(C, C)

# X = ones(3)     # doesn't work because it is a matrix
# conv3d(X, X)

Y = ones(4,3,2)
conv3d(Y, Y)
```



```{r}
library(RcppOctave)
library(rMRST)

A = ones(3)
.O$convn(A, A)

```

```{r}
B = ones(4, 3, 2)
for (i in 1:dim(B)[3]) {
    b <- .O$convn(B[,,i], B[,,i])
    print(b)
}
print(2*b)
```


```{r}

# Create two vectors of different lengths.
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)
column.names <- c("COL1","COL2","COL3")
row.names    <- c("ROW1","ROW2","ROW3")
matrix.names <- c("Matrix1","Matrix2")

# Take these vectors as input to the array.
result <- array(c(vector1,vector2), dim = c(3,3,2), 
                dimnames = list(row.names, 
                                column.names, 
                                matrix.names))


# print all matrices
# sapply(result, function(x) {x = seq(1, dim(result)[3])
#                                 result[,,x]})

for (i in 1:dim(result)[3])
    print(result[,,i])
```

```{r}
library(RcppOctave)
.O$convn(result[,,1], result[,,2])
```

```{r}
for (i in 1:dim(result)[3])
    print(.O$convn(result[,,i], result[,,i]))
```

```{r}
C = ones(5, 4, 3)

conv <- function(x) {
    x * .O$convn(C[,,x], C[,,x])
}

i <- seq(1, dim(C)[3])
j <- seq((dim(C)[3]-1):1)
#sapply(i, function(x) (x*.O$convn(C[,,x], C[,,x])) )
lapply(i, conv)
lapply(j, conv)
```

```{r}
# convolution of a 3 matrices returning an array
C = ones(5, 4, 3)
D <- array(0, dim = c(9,7,5))

for (i in 1:dim(C)[3]) {  # 1, 2, 3
    D[,,i] <- i *.O$convn(C[,,i], C[,,i])
}

for (j in (dim(C)[3]-1):1) {   # 2, 1
    D[,,i+(dim(C)[3]-j)] <- j *.O$convn(C[,,j], C[,,j])
}
D
```


```{r}
# convolution of a 3 matrices with for-loop
C = ones(5, 4, 3)

for (i in 1:dim(C)[3]) {
    print(i *.O$convn(C[,,i], C[,,i]))
}
for (i in (dim(C)[3]-1):1) {
    print(i *.O$convn(C[,,i], C[,,i]))
}
```


```{r}
C = ones(5, 4, 3)

for (i in 1:dim(C)[3]-1) {
    # b1 <- .O$convn(C[,,i], C[,,i])
    # print(b1)
    for (j in dim(C)[3]:1)
        print(j*.O$convn(C[,,i], C[,,j]))
}
# print(3*b1)
# print(2*b1)

```

