---
title: "3 fastest method to add rows to data frames"
output: html_notebook
---

```{r setup, include=F, error=T, message=F, warning=F}
knitr::opts_chunk$set(echo=T, comment=NA, error=T, warning=F, message = F, fig.align = 'center')
```

These three methods are the fastest in R to add rows.

          mkFrameDataTableLapply(nRow, nCol)
          mkFrameDataTableFor(nRow, nCol)
          mkFrameEnvDataTable(nRow, nCol)
        

These are the fastest methods to add rows to a data frame.        
        
```{r}
# From Arun Srinivasan's comment
# http://www.win-vector.com/blog/2015/07/efficient-accumulation-in-r/comment-page-1/#comment-65994
# library('data.table')

mkFrameDataTableLapply <- function(nRow, nCol) {
  # 1st fastest
  v <- lapply(seq_len(nRow),function(i) {
    mkRow(nCol)
  })
  data.table::rbindlist(v)
}

mkFrameDataTableFor <- function(nRow, nCol) {
  # 2nd fastest
  v = vector("list", nRow)
  for (i in seq_len(nRow)) {
    v[[i]] = mkRow(nCol)
  }
  data.table::rbindlist(v)
}



# Environments are mutable and tend to be faster than lists.
mkFrameEnvDataTable <- function(nRow,nCol) {
  # 3rd fastest
  e <- new.env(hash=TRUE,parent=emptyenv())
  for(i in seq_len(nRow)) {
    ri <- mkRow(nCol)
    assign(as.character(i), ri, envir = e)
  }
  data.table::rbindlist(as.list(e))
}

```


```{r}
library('microbenchmark')
source("plotBenchmarks.R")

set.seed(23525) # make run more repeatable

nCol <- 10                                  # number of columns for the test DF

mkRow <- function(nCol) {
  x <- as.list(rnorm(nCol))                           # list of random numbers
  x[[1]] <- ifelse(x[[1]] > 0, 'pos', 'neg')          # 1st column to be a string
  names(x) <- paste('x', seq_len(nCol), sep = '.')    # name the columns
  x                                                   # return a list
}


timeSeq <- seq.int(10, 200, 10)             # short sequence
timings <-  vector("list", length(timeSeq))


for(i in seq_len(length(timeSeq))) {
  nRow <- timeSeq[[i]]
  ti <- microbenchmark(
    mkFrameDataTableFor(nRow,nCol),
    mkFrameDataTableLapply(nRow,nCol),
    mkFrameEnvDataTable(nRow,nCol),
    times=10)
  ti <- data.frame(ti, stringsAsFactors=FALSE)
  ti$nRow <- nRow
  ti$nCol <- nCol
  timings[[i]] <- ti
}

timings <- data.table::rbindlist(timings)

print(plotTimings(timings))
```