---
title: "3D array convolution"
output: html_notebook
---


```{r}
convn3d <-  function(A, B) {
    dimA = dim(A)[1]
    dimB = dim(B)[1]
    dimC = dimA + dimB
    
    d1 = dim(A)
    d2 = dim(B)
    
    m  <- dim(a)[1]; n  <- dim(a)[2];  p  <- dim(a)[3]
    m1 <- dim(b)[1]; n1 <- dim(b)[2];  p1 <- dim(b)[3]
    
    mn <- d1 + 2 * (d2 - 1)
    
    C = array(0, dim = c(dimC, dimC, dimC))
    #C = array(0, dim = c(m1+m-1, n+n1-1, p+p1-1))   #<- causes error
    
    for (x1 in 1:dim(A)[1]) {
        for (x2 in 1:dim(B)[1]) {
            for (y1 in 1:dim(A)[2]) {
                for(y2 in 1:dim(B)[2]) {
                    for (z1 in 1:dim(A)[3]) {
                        for (z2 in 1:dim(B)[3]) {
                            x = x1 + x2
                            y = y1 + y2
                            z = z1 +  z2
                            C[x,y,z] = C[x,y,z] + A[x1,y1,z1] * B[x2,y2,z2]
                            #cat(x2,y2,z2, "\n")
                            
                        }
                    }
                }
                    
            }
        }
    }
    C
}    
```



```{r}
A <- array(1:18, dim = c(3,3,2))
B <- array(1:32, dim = c(4,4,2))

convn3d(A, B)
```




```{r}
# https://stackoverflow.com/questions/14786920/convolution-of-two-three-dimensional-arrays-with-padding-on-one-side-too-slow

A <- array(1:18, dim = c(3,3,2))
B <- array(1:32, dim = c(4,4,2))

dimA = dim(A)[1]
dimB = dim(B)[1]
dimC = dimA + dimB

d1 = dim(A)
d2 = dim(B)

m  <- dim(a)[1]; n  <- dim(a)[2];  p  <- dim(a)[3]
m1 <- dim(b)[1]; n1 <- dim(b)[2];  p1 <- dim(b)[3]

mn <- d1 + 2 * (d2 - 1)

C = array(0, dim = c(dimC, dimC, dimC))
#C = array(0, dim = c(m1+m-1, n+n1-1, p+p1-1))

for (x1 in 1:dim(A)[1]) {
    for (x2 in 1:dim(B)[1]) {
        for (y1 in 1:dim(A)[2]) {
            for(y2 in 1:dim(B)[2]) {
                for (z1 in 1:dim(A)[3]) {
                    for (z2 in 1:dim(B)[3]) {
                        x = x1+x2
                        y = y1 + y2
                        z = z1 +  z2
                        C[x,y,z] = C[x,y,z] + A[x1,y1,z1] * B[x2,y2,z2]
                        #cat(x2,y2,z2, "\n")
                        
                    }
                }
            }
                
        }
    }
}

C
```

