---
title: "print array with abind, lapply"
output: html_notebook
---

```{r}
D <- array(1:48, dim = c(4,4,3))
D
```


```{r}
library(abind)

# print a 3D array without a foor loop
abind(lapply(1:dim(D)[3], function(i) D[,,i]), along = 3)
```


https://stackoverflow.com/a/4310747/5270873

```{r}
x = cbind(1:2,3:4)
y = cbind(5:6,7:8)
x
y
```


## What is R's multidimensional equivalent of rbind and cbind?

```{r}
library(abind)
abind(x, y, along = 3)
```


```{r}
# for simple binding you can just manipulate the values directly, 
# based on the default ordering
array(c(x, y), dim = c(2, 2, 2))
```



```{r}
library(abind)

x<-array(1:36, c(2,9,2))
x

```

```{r}
# Extract 1st row:

asub(x, idx = list(1), dims = 1)
```




```{r}
# Extract second and third column:

asub(x, idx = list(2:3), dims = 2)
```


```{r}
# Remove the last item from dimension shortdim as the OP wanted:
shortdim = 3
asub(x, idx = list(1:(dim(x)[shortdim]-1)), dims = shortdim)
# this is equivalent to removing the last slice of the array
```


```{r}
# You can also use negative indexing so this will work too:

asub(x, idx = list(-dim(x)[shortdim]), dims = shortdim)
```

