---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, error=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=TRUE, comment=NA, error=TRUE, warning=FALSE, 
                      message = FALSE, fig.align = 'center')
```

# Define the class `Image`

```{r}
Grayscale = 0L
Color     = 2L


setClass ("Image",
  representation (colormode="integer"),
  prototype (colormode=Grayscale),
  contains = "array"
)

# constructor
Image = function(data = array(0, dim=c(1,1)), colormode = Grayscale) {
  
  return( new("Image", 
    .Data = data,
    colormode = colormode
  ))    
}

is.Image <- function (x) is(x, "Image")

# retrieve the data in the object
imageData = function (y) {
  if (is(y, 'Image')) y@.Data
  else y
}

# this method to assign data tot the object
`imageData<-` = function (y, value) {
  if (is(y, 'Image')) {
    y@.Data = value
    validObject(y)
    y
  } 
  else value
}
```




```{r}
img <- Image()
img
```

```{r}
is.Image(img)
```

```{r}
imageData(img)
```


```{r}
# assign matrix data using a method
imageData(img) <-  matrix(runif(25), nrow =5, ncol=5, byrow=TRUE)
img
```

```{r}
img <- Image(data = matrix(runif(36), nrow =6, ncol=6, byrow=TRUE))
img
```

```{r}
# get the data
imageData(img)
```

# Assigning a matrix of list 

## a list of integers

```{r}
img <- Image(data = matrix(list(1,2,3,5,6), nrow =2, ncol=3, byrow=TRUE))
img
```

## a list of dataframes

```{r}
img <- Image(data = matrix(list(data.frame(), data.frame(), data.frame()), nrow =3, ncol=1, byrow=TRUE))
img
```

```{r}
img[1]
```


## 

```{r}
a <- data.frame(unif = runif(36), unif2 = runif(36) * 2)
b <- data.frame(norm = rnorm(10), norm2 = rnorm(10) * 2)
c <- data.frame(weib = rweibull(5, 1), weib2 = rweibull(5,1) * 2)
```


```{r}
data_list <- matrix(list(a, b, c, nrow = 3, ncol = 1, byrow=TRUE))
```


```{r}
dists <- Image(data = data_list)
dists
```

```{r}
dists[1]
```


```{r}
dists[2]
```

```{r}
dists[4, 1] <- 2
dists
```

```{r}
slotNames("Image")
```



# Add a show method

```{r}

# utility functions
colorMode = function (y) {
  if (is(y, 'Image')) y@colormode
  else Grayscale
}

numberOfFrames = function(y, type = c('total', 'render')) {
    type = match.arg(type)
    type = switch(type, total = 0L, render = 1L)
    # .Call(C_numberOfFrames, y, type)
}

showImage = function (object, short=FALSE) {
  nd = dim(object)
  ld = length(nd)
  dimorder = names(dimnames(object))
  
  cat(class(object)[1],'\n')
  
  cat('  colorMode    :',c('Grayscale', NA, 'Color')[1+colorMode(object)],'\n')
  cat('  storage.mode :',typeof(object),'\n')
  cat('  dim          :',nd,'\n')
  if ( !is.null(dimorder) )
  cat('  dimorder     :',dimorder,'\n')
  cat('  frames.total :',numberOfFrames(object,'total'),'\n')
  cat('  frames.render:',numberOfFrames(object,'render'),'\n')
  
  if ( !isTRUE(short) ) {
    if (nd[1]>5) nd[1] = 5
    if (nd[2]>6) nd[2] = 6
    if (ld>2) nd[3:ld] = 1
    
    ndl = lapply(nd, seq_len)
    
    nds = paste0('[1:',nd[1],',1:',nd[2],paste(rep(',1',ld-2),collapse=''),']')
    
    cat('\nimageData(object)', nds, '\n', sep='')
    # print.default(asub(object@.Data, ndl))
  }
  invisible()
}

# replace show() by showImage()
setMethod ("show", signature(object = "Image"), function(object) showImage(object))
```

```{r}
Image()
```

