---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(purrr)
library(tidyr)
```


```{r}
iris
```

# Using dplyr

```{r}
n_iris <- iris %>% 
    group_by(Species) %>% 
    tidyr::nest() %>% 
    print
```


## reference
```{r}
n_iris$data[[1]]
n_iris$data[[2]]
n_iris$data[[3]]
```


## unnest

```{r}
n_iris %>% 
    unnest()
```



# using tidyr on whole table

## nest the whole table

```{r}
n_iris2 <- tidyr::nest(iris, .key = "iris")
n_iris2
```

## nest the table but keep *Species*

```{r}
n_iris3 <- tidyr::nest(iris, -Species, .key = "data")
n_iris3
```



## unnest

```{r}
tidyr::unnest(n_iris2)
```

## Using dplyr, tidyr and tibble

```{r}
library(dplyr)
as_tibble(iris) %>% 
    tidyr::nest(-Species)  # do not include Species variable
```

```{r}
tibble::as.tibble(iris)
```


# List column workflow

## 1. Make a list column

```{r}
n_iris <- iris %>% 
    group_by(Species) %>% 
    tidyr::nest() %>% 
    print
```

## 2. Work with list columns

```{r}
# create the function
mod_fun <- function(df)  
    lm(Sepal.Length ~ ., data = df) 

# apply the function
m_iris <- n_iris %>% 
  mutate(model = map(data, mod_fun))  # apply a function on the list column

m_iris
```

There is an additional list column `model`.

## 3. Simplify the list column

```{r}
b_fun <- function(mod)  
    coefficients(mod)[[1]]

m_iris %>% 
    # apply the function over the list column
    # transmute it's like mutate but keeps only the variables you create
    # in this example, only two columns are kept
    transmute(Species, beta = map_dbl(model, b_fun)) %>%  
    print()
```


# Making a list column with `tibble`

```{r}
library(tibble)
df <- tribble(
  ~max, ~seq, 
  3,    1:3, 
  4,    1:4, 
  5,    1:5)
df
```

## Reference the cell column
```{r}
df$seq[1]
df$seq[1][[1]]
df$seq[1][[1]][2]
```







