---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE, error=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=TRUE, comment=NA, error=TRUE, warning=FALSE, message = FALSE,
fig.align = 'center')
```


```{r}
# define the class
setClass("xyloc", slots = c(
                    x="numeric", 
                    y="numeric"))

# Creation can use existing classes:
setClass("fungi", slots = c(
                  species = "character"),
         contains = "xyloc"
)
```


```{r}
# direction implementation
field1 <- new("fungi", x = runif(25), y = runif(25),
              species = sample(letters[1:5], 25, rep=T))
```


```{r}
# using a constructor
fungi <- function(x, y, species)
  new("fungi", x=x, y=y, species=species)
```


```{r}
# validity
validFungi <- function(object) {
  len <- length(object@x)
  if(length(object@y) != len || length(object@species) != len)
    return("mismatch in lengths of slots")
  else return(TRUE)
}

setValidity("fungi", validFungi)

# dumpClass("fungi")
# !cat fungi.class.q
```


```{r}
getSlots("fungi")
slotNames("fungi")
# hasSlot(field1, "x")
```


```{r}
# implement using the constructor
# new("fungi")
field2 <- fungi(x = runif(25), y = runif(25),
              species = sample(letters[1:5], 25, rep=T))
```


```{r}
# the show method
show.fungi <- function(object) {
  tmp <- rbind(x = format(round(object@x, 2)),
               y = format(round(object@y, 2)),
               species = object@species)
  dimnames(tmp)[[2]] <- rep("", length(object@x))
  print(tmp, quote=F)
  invisible(object)
}
setMethod("show", "fungi", show.fungi)

removeMethod("show", "fungi")
```

```{r}
print.fungi <- function(x, digits=2) {
  tmp <- rbind(x = format(round(x@x, digits)),
               y = format(round(x@y, digits)),
               species = x@species)
  if(!is.null(tmp)) {
    dimnames(tmp)[[2]] = rep("", length(x@x))
    print(tmp, quote=F)
  } else cat("empty object of class fungi\n")
  invisible(x)
}
```



```{r}
setMethod("show", "fungi", function(object) print.fungi(object))

show(field1)

```

