---
title: "R Notebook"
output: html_notebook
---

```{r}
library(h5)

aFile <- file.path("./", "test.h5")
if (file.exists(aFile)) file.remove(aFile)

# 1. Create/Open file 'test.h5' (mode set to 'a'ppend)
file <- h5file(aFile, 'a')

# 2. Store character vector in group '/test' and dataset 'testvec'
file["test/testvec"] <- LETTERS[1:9]

# Store integer matrix in group '/test/testmat' and dataset 'testmat'
mat <- matrix(1:9, nrow = 3)
rownames(mat) <- LETTERS[1:3]
colnames(mat) <- c("A", "BE", "BUU")
file["test/testmat/testmat"] <- mat

# Store numeric array in group '/test' and dataset 'testarray'
file["test/testarray"] <- array(as.numeric(1:45), dim = c(3, 3, 5))

# 3. Store rownames and column names of matrix as attributes
# Get created data set as object
dset <- file["test/testmat/testmat"]

# Store rownames in attribute 'dimnames_1'
h5attr(dset, "dimnames_1") <- rownames(mat)

# Store columnnames in attribute 'dimnames_2'
h5attr(dset, "dimnames_2") <- colnames(mat)


# 4. Read first 3 elements of testvec
testvec <- file["test/testvec"]
testvec[1:3]

# Read first 2 rows of testmat
testmat <- file["test/testmat/testmat"]
res <- testmat[1:2, ]

# attach rownames and columnnames
rownames(res) <- attr(testmat, "rownames")[1:2]
colnames(res) <- attr(testmat, "colnames")

# 5. Extend testvec
testvec <- c(testvec, LETTERS[10:26])

# Retrieve entire testvec
testvec[]

# 6. Close open handles
h5close(testvec)
h5close(testmat)
h5close(file)
```

## common FG

```{r}
aFile <- file.path("./", "test_FG.h5")
if (file.exists(aFile)) file.remove(aFile)

file <- h5file(aFile)

# Create new DataSet 'testset' in H5Group 'testgroup'
file["testgroup/testset"] <- matrix(1:9, nrow = 3)

# Create new DataSet 'testset2' in file root
file["testset2"] <- 1:10

# Retrieve H5Group 'testgroup'
group <- file["testgroup"]

# Retrieve DataSet 'testset'
dset <- group["testset"]
h5close(dset)
h5close(group)
h5close(file)
#file.remove(aFile)
```


## File objects

```{r}
aFile <- file.path("./", "test1_Fo.h5")
if (file.exists(aFile)) file.remove(aFile)

# The following examples generates a HDF5 file with the different HDF5
# Objects and shows its contents:
file <- h5file(name = aFile, mode = "a")
file["testdataset"] <- 1:10
h5attr(file, "testattrib") <- LETTERS[1:10]
file["testgroup/testdataset2"] <- 1:10
file
# Close file and delete
h5close(file)
# if(file.exists("test.h5")) file.remove("test.h5")


# The following example shows hdf5 file contents and how to use them to iterate over HDF5 elements:
aFile <- file.path("./", "test2_Fo.h5")
if (file.exists(aFile)) file.remove(aFile)

file <- h5file(name = aFile, mode = "a")
file["testgroup1/testset1"] <- 1:10
file["testgroup2/testset2"] <- 11:20
file["testgroup3/testset3"] <- 21:30

# Extract first 3 elements from each dataset and combine result to matrix
sapply(list.datasets(file, recursive = TRUE), function(x) file[x][1:3])

# Add new dataset to each group in HDF5 file
for(g in list.groups(file)) {
  file[paste(g, "testsetx", collapse = "/")] <- 1:10
}
list.datasets(file, recursive = TRUE)
list.groups(file, recursive = TRUE)
list.attributes(file)
# Close file
h5close(file)
```

## location, attribute
```{r}
aFile <- file.path("./", "test_LA.h5")
if (file.exists(aFile)) file.remove(aFile)

# Write Attributes for H5File, H5Group and DataSet
file <- h5file(aFile)
h5attr(file, "fileattrib") <- 1:10
group <- file["testgroup"]
h5attr(group, "groupattrib") <- matrix(1:9, nrow = 3)
h5attr(group, "groupattrib")
group["testdataset"] <- 1:10
dset <- group["testdataset"]
h5attr(dset, "dsetattrib") <- LETTERS[1:10]
h5close(dset)
h5close(group)
h5close(file)
```

```{r}
aFile <- file.path("./", "test_DS.h5")
if (file.exists(aFile)) file.remove(aFile)

# Write Attributes for H5File, H5Group and DataSet
file <- h5file(aFile)
createDataSet(file, "ints", c(100,5))
h5close(file)
```


## CommonFG-DataSet {h5}

```{r}
aFile <- file.path("./", "test.h5")
if (file.exists(aFile)) file.remove(aFile)

file <- h5file(aFile)

# Create new DataSet 'testset' in H5Group 'testgroup'
file["testgroup/testset"] <- matrix(1:9, nrow = 3)

# Create new DataSet 'testset2' in file root
file["testset2"] <- 1:10

# Retrieve H5Group 'testgroup'
group <- file["testgroup"]

# Retrieve DataSet 'testset'
dset <- group["testset"]

# list datasets
list.datasets(file, "/")

## S4 method for signature 
## 'CommonFG,character,ANY,missing,missing,ANY,ANY,ANY,missing'
createDataSet(file,
  "datasetname", 1:10)

h5close(dset)
h5close(group)
h5close(file)
# file.remove(aFile)


```

