---
title: "R Notebook"
output: html_notebook
---


https://stackoverflow.com/a/30007964/5270873


## Build a list of matrices

```{r}
matrix( list(c(1,2,4), c(NULL), c(1,2), c(3,4,5,6), c(1), c(1,3)), 
        nrow=2, 
        ncol=3)

# notice that the matrix-list doesn't have a [i,j] index but [i*j]
```

```{r}
Mlist <- matrix( list(c(1,2,4), c(NULL), c(1,2), c(3,4,5,6), c(1), c(1,3)), 
                 nrow=2, ncol=3)
Mlist[1,1]
# 1 2 4
```

```{r}
is.matrix(Mlist)
class( Mlist[1,1] )
```

## Demonstration of creating "matrix of lists" from a list:

```{r}
# create a list first
will.become.a.matrix <- list(c(1,2,4), c(NULL), c(1,2), c(3,4,5,6), c(1), c(1,3))
is.matrix(will.become.a.matrix)
```

### add the `dim` attribute to the list

```{r}
dim(will.become.a.matrix) <- c(2,3)
is.matrix(will.become.a.matrix)
# now list is a matrix
```

```{r}
dim(will.become.a.matrix)        # 2x3
class(will.become.a.matrix)      # matrix
class(will.become.a.matrix[1,1]) # list
```

## Example: creating a matrix of lists

```{r}
 A      <- list();    F      = list();     E      = list()
 A[1]   <- c(3) ;     F[[1]] <-numeric(0); E[[1]] <- numeric(0)
 A[2]   <- c(1) ;     F[2]   <-c(1)   ;    E[2]   <- c(1)
 A[3]   <- c(1) ;     F[3]   <-c(2)  ;     E[[3]] <- numeric(0)
 A[[4]] <- list(1,3); F[[4]] <-numeric(0); E[[4]] <- numeric(0)
 A[5]   <- c(4) ;     F[5]   <-c(4)      ; E[5]   <- c(4)
 
 Mlist = c(A, F, E)                     # collection of lists
 M <- matrix(Mlist, length(A), 3)       # convert list to matrix
#=====================================
 class(Mlist)
 class(M)
 M
 # it will not look readable but it is a matrix of lists
```

## 
```{r}
#               six lists arranged in 2x3
b <- matrix(rep(list(), 6), nrow = 2, ncol = 3) 
b
#.... then replace the NULL items with values. 
# Need to use "[[": for assignment (which your 'Update 1' did not 
# ....and your Update2 only did for some but not all of the assignments.)

```

```{r}
b[[1]] <- c(1,2,3,4)   # store a vector in list #1
b[[2]] <- matrix(rnorm(4), 2, 2)
b
```




```{r}
# print the contents of the matrix
apply(b, c(1,2), function(x) paste(eval(parse(text=x)), collapse = " "))
```

```{r}
# use length of the matrix instead of c(1,2)
length(dim(b))
apply(b, 1:length(dim(b)), function(x) paste(eval(parse(text=x)), collapse = " "))
```

```{r}
# get the values in the matrix-list
apply(b, 1:length(dim(b)), function(x) eval(parse(text=x)))
```

## array-lists

```{r}
# array-list
ar <- array(rep(list(), 6), dim = c(4,3,2)) 
ar
```

```{r}
# store a vector and a matrix in the array-list
ar[[1]] <- c(1,2,3,4)   # store a vector in list #1
ar[[2]] <- matrix(rnorm(4), 2, 2)
ar
```

```{r}
# get the values in the array-list
# apply(ar, 1:length(dim(ar)), function(x) eval(parse(text=x)))
apply(ar, 1:length(dim(ar)), function(x) eval(parse(text=x)) )
```


## dynamic way to allocate the matrix-list

```{r}
c = c(1,2,3); d = c(9,8,7,6);   # define the vectors
CD <- matrix(rep(list(), (length(d) * length(c))), nrow = length(c), ncol =length(d))
dim(CD)
CD
cat("\n")

# assign values to the matrix-list
i = 1; j = 1
# CD[i, j] <- c(1,2,3,4)                                 <- this will not work
CD[[i + nrow(CD)*(j-1)]] <- c(1,2,3,4)

i = 3; j = 1
CD[[i + nrow(CD)*(j-1)]] <- array(1, dim = c(4,3,2))

i = 3; j = 2
CD[[i + nrow(CD)*(j-1)]] <- c(10)

i = 1; j = 4;
CD[[i + nrow(CD)*(j-1)]] <- matrix(c(9),1,1)

i = 3; j = 4
CD[[i + nrow(CD)*(j-1)]] <- c(99,98)
CD
```

```{r}
# extracting elements from a list using list-indices
idx = list(c(1,3,6))
do.call( `[`, c(list(CD), idx)) 
```

```{r}
# extracting elements from a list using list-indices
idx = list(c(1,1), c(3,4))
do.call( `[`, c(list(CD), idx)) 
```

```{r}
# access the values
i = 3; j = 2
CD[[i+nrow(CD)*(j-1)]]

```

```{r}
CD[3, 2]
```

## Double behavior: as a matrix and as a list
```{r}
class(CD[3,4])
CD[3,4]         # show the content
CD[[3 + nrow(CD)*(4-1)]]       # get the content
class(CD[[3 + nrow(CD)*(4-1)]] )
```


```{r}
# extract the values from the matrix-list
i = 3; j = 1
CD[[i + nrow(CD)*(j-1)]]
```



