---
title: "R Notebook"
output: html_notebook
---


```{r}
library(rJava)

ospJarFile <- paste("./inst/ospjar", "osp.jar", sep = "/")
ospJarFile

.jinit()          # initialize Java-VM
.jaddClassPath(ospJarFile)
.jclassPath()
```

```{r}
library(rJava)
ospClasses <- "./inst/osp" 
.jinit()          # initialize Java-VM
.jaddClassPath(ospClasses)
.jclassPath()

tf <- .jnew("org/opensourcephysics/frames/TableFrame", "TableFrame")
tf$setRowNumberVisible(FALSE)
tf$setColumnNames(as.integer(1), "x")
tf$setColumnNames(as.integer(2), "sqrt(x)")
tf$setColumnNames(as.integer(3), "cube root(x)")
tf$setName("one")

for (i in seq(0, 10, 1)) {
    tf$appendRow(c(i, sqrt(i), i^(1/3)))
}
tf$appendRow(c(1,2,3))
tf$appendRow(c(3,4,5))
# tf$appendRow(matrix(1:5, nrow = 1))
tf$setVisible(TRUE)
```


```{r}
tableFrame <- .jnew("org/opensourcephysics/frames/TableFrame", "TableFrame")

```

```{r}
strings <- .jarray( c("string", "array") )


tableFrame$setRowNumberVisible(FALSE)
tableFrame$setTitle("my table")
# tableFrame$setColumnNames(strings)
# tableFrame$setColumnNames(list(c("1", "2")))

# tableFrame$setColumnNames(0, "x");
# tableFrame$setColumnNames(1, "square root");
# tableFrame$setColumnNames(2, "cube root");

# .jcall(tableFrame,, "setColumnNames", c("one", "two"))
# .jcall(tableFrame,, "setColumnNames", strings)
# .jcall(tableFrame,, "setColumnNames", strings)
# tableFrame$setColumnNames(as.integer(0), "sq")
tableFrame$setVisible(TRUE)
#tableFrame$setDefaultCloseOperation(tableFrame$EXIT_ON_CLOSE);
```

```{r}
strings <- .jarray( c("string", "array") )
strings
l <- new( J("javax.swing.JList"), strings)
l
```



    TableFrame tableFrame = new TableFrame("Root Table");
    tableFrame.setRowNumberVisible(false);
    tableFrame.setColumnNames(0, "x");
    tableFrame.setColumnNames(1, "square root");
    tableFrame.setColumnNames(2, "cube root");



