---
title: "R Notebook"
output: html_notebook
---

http://darrkj.github.io/blog/2015/jan182015/

```{r}
library(R6)
library(rbenchmark)
# library(jvmr)

Queue_R6 <- R6Class("Queue",
  public = list(
      data = NA,
      initialize = function(data) {
        if (!missing(data)) {
            self$data <- as.list(data)
        } else {
            self$data <- list()
        }
      },
      #
      size = function() length(self$data),
      #
      push = function(item) self$data[[self$size() + 1]] <- item,
      #
      pop = function() {
          if (self$size() == 0) return(NULL) # stop("queue is empty!")
          value <- self$data[[1]]
          self$data[[1]] <- NULL
          value
      }
  )
)
```


```{r}
q_comp <- function(str, num = 100) {
  eval(parse(text = paste0('x <- ', str)))
  for(i in seq(num)) x$push(i)
  for(i in seq(num)) x$pop()
}

benchmark(replications = rep(100, 3),
          # q_comp('Queue_RC$new()'), 
          q_comp('Queue_R6$new()'),
          columns = c('test', 'elapsed', 'replications', 'relative'))
```


