---
title: "R Notebook"
output: html_notebook
---


## 1
https://stackoverflow.com/questions/22182048/error-in-r-s4-setreplacemethod

```{r}
setClass(Class = "A",
     representation = representation(x = "numeric"),
     prototype = prototype(x = 0))

setReplaceMethod(f = "[",
             signature = "A",
             definition = function(x, i, j, value) {
                 return(x)
             })

# setReplaceMethod(f="[", 
#                  signature="A", 
#                  function(x, i, j, ..., value) { 
#                      return(x) 
#                      })
```


## 2
https://cran.r-project.org/doc/contrib/Genolini-S4tutorialV0-5en.pdf


```{r}
setClass(Class="Trajectories", 
         representation(times="numeric", traj="matrix"), 
         validity=function(object) { 
             cat("~~~ Trajectories: inspector ~~~ \n") 
             if(length(object@times)!=ncol(object@traj)) { 
                 stop("[Trajectories: validation] number of temporal meas. not correspond") 
                 } else { }
             return(TRUE)
        })


setGeneric("getTimes",function(object){standardGeneric ("getTimes")})
setMethod("getTimes","Trajectories",
 function(object) {
    return(object@times)
 })

setGeneric("setTimes<-", function(object, tol){standardGeneric("setTimes<-")})
setReplaceMethod(f="setTimes", signature="Trajectories", 
                 definition=function(object, tol){ 
                     object@times <- tol
                     return (object)
})


traj <- new(Class="Trajectories",times=1:3, traj=matrix(1:3,ncol=3))
setTimes(traj) <- 1:4
getTimes(traj)
```


## 3

https://stackoverflow.com/questions/22546638/slot-assignment-vs-slot-vs-setreplacemethod

```{r}
setClass("MyClass", 
                 representation(MySlot="numeric"))

setGeneric("MySlot", function(object) {
    standardGeneric("MySlot")
})

setMethod("MySlot",
      signature = "MyClass",
      definition = function(object) {
          return(object@MySlot)
})

setGeneric("MySlot<-",
       function(object, value) {
           standardGeneric("MySlot<-")
})

setReplaceMethod("MySlot",
             signature="MyClass",
             function(object, value) {
                 object@MySlot<- value
                 validObject(object) # could add other checks
                 return(object)
})

mc <- new("MyClass")
MySlot(mc) <- 3

mc@MySlot
```

