---
title: "R Notebook"
output: html_notebook
---

## Class definition

```{r}
setClass("SNPLocations", 
         slots = c(
           genome = "character",
           snpid = "character",
           chrom = "character",
           pos = "integer"
         )
)

```


## Constructor
```{r}
SNPLocations <- function(genome, snpid, chrom, pos) 
  new("SNPLocations", genome = genome, snpid = snpid, chrom = chrom, pos = pos)


```


```{r}
snplocs <- SNPLocations(genome = "hg19",
                        snpid = c("rs001", "rs0002"),
                        chrom = c("chr1", "chrX"),
                        pos = c(22433L, 1266886L)
                        )
```


## Defining the `length` method
```{r}
setMethod("length", "SNPLocations", function(x) length(x@snpid))
```

```{r}
# test the method
length(snplocs)
```

## slot getters

```{r}
setGeneric("genome", function(x) standardGeneric("genome"))
setMethod("genome", "SNPLocations", function(x) x@genome)

setGeneric("snpid", function(x) standardGeneric("snpid"))
setMethod("snpid", "SNPLocations", function(x) x@snpid)

setGeneric("chrom", function(x) standardGeneric("chrom"))
setMethod("chrom", "SNPLocations", function(x) x@chrom)

setGeneric("pos", function(x) standardGeneric("pos"))
setMethod("pos", "SNPLocations", function(x) x@pos)
```

```{r}
# using the getters
genome(snplocs)
snpid(snplocs)
chrom(snplocs)
pos(snplocs)
```

## Defining the `show` method

```{r}
setMethod("show", signature = "SNPLocations",
          function(object)
            cat(class(object), "instance with", length(object),
                "SNPs on genome", genome(object), "\n")
            )
```


```{r}
snplocs
```

## Defining the validity method

```{r}
setValidity("SNPLocations",
  function(object) {
    if (!is.character(genome(object)) || 
        length(genome(object)) != 1 || is.na(genome(object))) 
      return("'genome' slot must be a single string") 
    slot_lengths <- c(length(snpid(object)), 
                      length(chrom(object)), 
                      length(pos(object)))
    if (length(unique(slot_lengths)) != 1)
      return("lengths of slots 'snpid', 'chrom' and 'pos' differ")
    TRUE
  }
)

```

```{r}
snplocs@chrom <- LETTERS[1:3] # a very bad idea!

validObject(snplocs)
```

## Defining slot `setters`
```{r}
setGeneric("chrom<-", function(x, value) standardGeneric("chrom<-"))
setReplaceMethod("chrom", "SNPLocations", 
                 function(x, value) {x@chrom <- value; validObject(x); x})
```

```{r}
# these two will cause an error
chrom(snplocs) <- LETTERS[1:2] # repair currently broken object

chrom(snplocs) <- LETTERS[1:3] # try to break it again

# Error in validObject(x) : invalid class “SNPLocations” object: lengths of slots 
# 'snpid', 'chrom' and 'pos' differ
```

```{r}
# now this will work
chrom(snplocs) <- c("chr2", "chrY")
```


## Defining a coercion method

```{r}
setAs("SNPLocations", "data.frame", 
      function(from) 
        data.frame(snpid=snpid(from), chrom=chrom(from), pos=pos(from))
)      
```

```{r}
as(snplocs, "data.frame")
```

