---
title: "Racquetball game with S4 classes"
output: html_notebook
---

This example extracted from Zelle's book on Python.

```{r}
source("./R/RBall.R")
```


## Play the game, silent
Non-verbose, only summary at the end of the games

```{r}
# The whole program using S4 classes
n <-  5        # play fifty games

# Each game ends when a player defeats another by 7-0 or the first that reaches 15 points.

stats <- SimStats()
for (i in 1:n) {   # play `n` games
    theGame <- RBallGame(0.5, 0.5, verbose = FALSE)
    theGame <- play(theGame)
    stats   <- Update(stats, theGame)
}
printReport(stats)
```


## Play the game, verbose 
Verbose plus summary at the end of the games

```{r}
# The whole program using S4 classes
n <-  5        # play fifty games

# Each game ends when a player defeats another by 7-0 or the first that reaches 15 points.

stats <- SimStats()
for (i in 1:n) {   # play `n` games
    theGame <- RBallGame(0.5, 0.5, verbose = TRUE)
    theGame <- play(theGame)
    stats   <- Update(stats, theGame)
}
printReport(stats)
```








```{r}
# test one player
p <- Player(0.5, "A")
result <- ""

for (i in 1:10) {
    if (winsServe(p)) {
        result <- "WIN"
        p <- incScore(p)
    } else {
        result <-  "LOSE"
    }
    cat(sprintf("%5d %3s %3d %8s \n", i, whois(p), getScore(p), result))
}
```


```{r}
# test RBallGame class. Results for one game only
game <- RBallGame(0.49, 0.51, verbose = TRUE)
game <- play(game)
```
