---
title: "Pendulum with EulerRichardson ODE solver"
output: html_notebook
---

```{r}
#
# ############################################################  Test Pendulum
library(testthat)

source("./R/ode_generics.R")
source("./R/EulerRichardson.R")
source("./R/Pendulum.R")                   # this script uses Euler-Richardson

ode <- new("ODE")
pendulum <- Pendulum()

dt <- 0.1
theta <- 0.2
thetaDot <- 0

pendulum@state[3] <- 0      # set time to zero, t = 0

pendulum <- setState(pendulum, theta, thetaDot)
# stepSize <- dt
pendulum <- setStepSize(pendulum, dt = dt)    # needs explicit declaration of dt

state <- c(0.2, 0.0, 0.0)

# 
# 
expect_equal(pendulum@odeSolver@ode@state, c(0.2, 0.0, 0.0))

    expect_equal(getStepSize(pendulum@odeSolver), 0.1) # get default step size

    # ----------------------------------------- these two vars hold no values
    # expect_true(length(pendulum@state) == 0)
    expect_true(length(pendulum@rate)  == 0)

    # +++++++++++++++++++++++++++++++++++++++++ values stored here
    expect_true(all(pendulum@odeSolver@ode@state == state))
    expect_true(length(pendulum@odeSolver@ode@rate) == 3)

pendulum@odeSolver <- init(pendulum@odeSolver, 0.123)
    expect_equal(getStepSize(pendulum@odeSolver), 0.123)

    expect_equal(pendulum@odeSolver@ode@state, state)
    expect_equal(pendulum@odeSolver@numEqn, 3)

pendulum@odeSolver <- setStepSize(pendulum@odeSolver, dt) # set new step size
    expect_equal(getStepSize(pendulum@odeSolver), dt)

    expect_true(!is.null(step(pendulum@odeSolver))) # step Euler returns a value
    expect_true(length(ode@rate)  == 0)

rate <- c(0, 0, 0)
rate <- vector("numeric")
    expect_equal(getRate(pendulum@odeSolver@ode, state, rate),
                 c(0, -0.596008, 1))

    expect_equal(getStepSize(pendulum@odeSolver), dt)

while (pendulum@state[3] <= 100)    {
    pendulum <- step(pendulum)
    cat(sprintf("%12f %12f %12f \n", pendulum@state[1], 
                pendulum@state[2], pendulum@state[3]))
}
```

```{r}
# Using Euler
# 
#
# ####################################################  Test Pendulum with Euler
library(testthat)

source("./R/ode_generics.R")
source("./R/Euler.R")
source("./R/PendulumE.R")       # Pendulum script with ODE EUler

ode <- new("ODE")
pendulum <- Pendulum()

dt <- 0.1
theta <- 0.2
thetaDot <- 0

pendulum@state[3] <- 0      # set time to zero, t = 0

pendulum <- setState(pendulum, theta, thetaDot)
stepSize <- dt
pendulum <- setStepSize(pendulum, stepSize)

state <- c(0.2, 0.0, 0.0)

# 
# 
expect_equal(pendulum@odeSolver@ode@state, c(0.2, 0.0, 0.0))

    expect_equal(getStepSize(pendulum@odeSolver), 0.1) # get default step size

    # ----------------------------------------- these two vars hold no values
    # expect_true(length(pendulum@state) == 0)
    expect_true(length(pendulum@rate)  == 0)

    # +++++++++++++++++++++++++++++++++++++++++ values stored here
    expect_true(all(pendulum@odeSolver@ode@state == state))
    expect_true(length(pendulum@odeSolver@ode@rate) == 3)

pendulum@odeSolver <- init(pendulum@odeSolver, 0.123)
    expect_equal(getStepSize(pendulum@odeSolver), 0.123)

    expect_equal(pendulum@odeSolver@ode@state, state)
    expect_equal(pendulum@odeSolver@numEqn, 3)

pendulum@odeSolver <- setStepSize(pendulum@odeSolver, dt) # set new step size
    expect_equal(getStepSize(pendulum@odeSolver), dt)

    expect_true(!is.null(step(pendulum@odeSolver))) # step Euler returns a value
    expect_true(length(ode@rate)  == 0)

rate <- c(0, 0, 0)
rate <- vector("numeric")
    expect_equal(getRate(pendulum@odeSolver@ode, state, rate),
                 c(0, -0.596008, 1))

    expect_equal(getStepSize(pendulum@odeSolver), dt)

while (pendulum@state[3] <= 100)    {
    pendulum <- step(pendulum)
    cat(sprintf("%12f %12f %12f \n", pendulum@state[1], 
                pendulum@state[2], pendulum@state[3]))
}
```


```{r}
# ######################################################### Test EulerRichardson
# Euler-Richardson class does not implement getState() and getRate() 
# as in the case of Euler
library(testthat)

source("./R/ode_generics.R")
source("./R/ODE.R")
source("./R/EulerRichardson.R")

state <- c(0, 1, 3)
rate  <- c(0, 0, 0)
stepSize <- 0.1

ode <- new("ODE")

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ test constructor

expect_error(EulerRichardson(), 'argument ".ode" is missing, with no default')

eulerRichardson <- EulerRichardson(ode)

eulerRichardson@ode@state <-  state                # set a vector for state


# ----------------------------------------- these two vars hold no values
expect_true(length(ode@state) == 0)
expect_true(length(ode@rate)  == 0)

#                                                  values stored here in ode
expect_true(all(eulerRichardson@ode@state == state))
expect_true(length(eulerRichardson@ode@rate) == 0)

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ test init()
eulerRichardson <- init(eulerRichardson, stepSize)

expect_equal(eulerRichardson@stepSize, stepSize)      # test stepSize

expect_equal(eulerRichardson@ode@state, state)
expect_equal(eulerRichardson@numEqn, 3)               # number of equations

expect_true(!is.null(step(eulerRichardson)))    # step returns a value not NULL
expect_true(length(ode@rate)  == 0)                     # rate still empty
expect_equal(getRate(eulerRichardson@ode), c(0, 0, 0))  # rate has a vector

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ test step()
#                                rate is zero until we run setState and getRate
expect_equal(eulerRichardson@midstate, c(0, 0, 0))  # midpoint before step

eulerRichardson <- step(eulerRichardson) 
expect_equal(eulerRichardson@ode@state, state)
expect_equal(eulerRichardson@ode@rate, rate)
expect_equal(eulerRichardson@midstate, state)       # midpoint after step

eulerRichardson <- step(eulerRichardson)
expect_equal(eulerRichardson@ode@state, state)
expect_equal(eulerRichardson@ode@rate, rate)
expect_equal(eulerRichardson@midstate, state)       # midpoint after step

eulerRichardson <- step(eulerRichardson)
expect_equal(eulerRichardson@ode@state, state)
expect_equal(eulerRichardson@ode@rate, rate)
expect_equal(eulerRichardson@midstate, state)       # midpoint after step

eulerRichardson <- step(eulerRichardson) 
expect_equal(eulerRichardson@ode@state, state)
expect_equal(eulerRichardson@ode@rate, rate)
expect_equal(eulerRichardson@midstate, state)       # midpoint after step

# eulerRichardson@ode@state
# eulerRichardson@ode@rate
# 
# getState(eulerRichardson@ode)
# 
# getRate(eulerRichardson@ode, eulerRichardson@ode@state, eulerRichardson@ode@rate)

```

