---
title: "R Notebook"
output: html_notebook
---

## New R file `FallingParticleApp.R`

```{r}
# testing FallinParticleODE by creating a loop doing the stepping.
# The stepping is usually controllled by the ODE solver which could
# be Euler, Euler-Richardson

source("./R/FallingParticleApp.R")


# state <- c(1, 0, 0)
rate <- c(0, 0, 0)

ball <- FallingParticleODE(10, 0)
# Slot "state":
# [1] 10  0  0             # with return(.Object)

ball@g
state <- getState(ball)
state

rate <- getRate(ball, state, rate)
rate

stepSize <- 0.1
numEqn <- length(state)

# this loop will stop when ball@state[1] is zero or lower
while (ball@state[1] > 0) {
    # start the step()
    state <- getState(ball)
    rate  <- getRate(ball, state, rate)

    for (i in 1:numEqn) {
        state[i] <- state[i] + stepSize * rate[i]
        cat(sprintf("%3d %10f %10f \n", i, state[i], rate[i]))

    }
    ball@state <- state
    ball@rate <-  rate
}

```


```{r}

source("./R/FallingParticleApp.R")
# source("./R/Euler.R")

initial_y <- 10
initial_v <- 0
dt <- 0.01
rate <- c(0,0,0)

ball <- FallingParticleODE(initial_y, initial_v)

eusolver <- Euler(ball)
eusolver <- setStepSize(eusolver, dt)

# getState(ball)
eusolver@ode@state
eusolver@ode@rate
eusolver <- step(eusolver)
eusolver@ode@state
eusolver@ode@rate
# state <- getState(ball)
# rate <- getRate(ball, state, rate)
# # getRate(ball, state, rate)
# rate
```



```{r}
source("./R/FallingParticleApp.R")
# source("./R/Euler.R")

initial_y <- 10
initial_v <- 0
dt <- 0.01

ball <- FallingParticleODE(initial_y, initial_v)
ball@g == 9.8
ball@state == c(10, 0, 0)
ball@rate

eusolver <- Euler(ball)
eusolver <- setStepSize(eusolver, dt)

eusolver@stepSize == getStepSize(eusolver)

eusolver@ode@rate == c(0, 0, 0)
eusolver <- step(eusolver)
# 
eusolver@ode@state
rate <- eusolver@ode@rate

# for (i in 1:10) {
while (ball@state[1] > 0) {
    eusolver <- step(eusolver)
    ball <- eusolver@ode
    cat(sprintf("%12f %12f \n", ball@state[1], ball@rate[1] ))
    # cat(ball@state[1], "\n")
}
```


```{r}
source("./R/Euler.R")

eusolver <- Euler(ball)
# eusolver@rate
eusolver@stepSize
eusolver@numEqn

step(eusolver)
```




## Test of FallinParticleODE

```{r}
# testing FallinParticleODE by creating a loop doing the stepping.
# The stepping is usually controllled by the ODE solver which could
# be Euler, Euler-Richardson

source("./R/FallingParticleODE.R")


# state <- c(1, 0, 0)
rate <- c(0, 0, 0)

ball <- FallingParticleODE(10, 0)
# Slot "state":
# [1] 10  0  0             # with return(.Object)

ball@g
state <- getState(ball)
state

rate <- getRate(ball, state, rate)
rate

stepSize <- 0.1
numEqn <- length(state)

# this loop will stop when ball@state[1] is zero or lower
while (ball@state[1] > 0) {
    # start the step()
    state <- getState(ball)
    rate  <- getRate(ball, state, rate)

    for (i in 1:numEqn) {
        state[i] <- state[i] + stepSize * rate[i]
        cat(sprintf("%3d %10f %10f \n", i, state[i], rate[i]))

    }
    ball@state <- state
    ball@rate <-  rate
}

```








```{r}
source("./R/FallingParticleODE.R")
source("./R/Euler.R")

ball <- FallingParticleODE(initial_y, initial_v)

solver <- Euler(ball)
solver <- setStepSize(solver, dt)

solver <- step(solver)
cat(solver@ode@state[1], solver@ode@state[2], solver@ode@state[3], "\n")
# cat("ball@state:", ball@state[1], ball@state[2], ball@state[3],"\n")

solver <- step(solver)
cat(solver@ode@state[1], solver@ode@state[2], solver@ode@state[3], "\n")
```


```{r}
source("./R/Euler.R")
source("./R/FallingParticleODE.R")

ball <- FallingParticleODE(10, 0)
# class(ball)

solver <- Euler(ball)
```




```{r}
source("./R/Euler.R")
source("./R/FallingParticleODE.R")

ball <- FallingParticleODE(10, 0)

solver <- Euler(ball)
solver <- setStepSize(solver, 0.01)
    
ball@state[1] > 0
# solver <- step(solver)
step(solver)
# ball@state[1]
ball
```

```{r}
solver <- step(solver)
cat("ball@state:", ball@state[1], ball@state[2], ball@state[3],"\n")
```


```{r}
solver <- step(solver)
ball <- solver@ode
ball
# cat("ball@state[1]", ball@state[1], "\n")
# ball@state[2]
# ball@state[3]
# solver@ode@state
# solver@ode@rate
```

```{r}
source("./R/Euler.R")

solver <- Euler(ball)
solver <- setStepSize(solver, 0.01)
    
ball@state[1] > 0
# solver <- step(solver)
step(solver)
# ball@state[1]
ball
```


```{r}
source("./R/FallingParticleODE.R")

# state <- c(1, 0, 0, 6.28, 0)

rate <- c(0, 0, 0)

ball <- FallingParticleODE(10, 0)


# ball
state <- getState(ball)
getRate(ball, state, rate)
# ball@rate
# ball@state
```


```{r}
# ball@state <- c(2, 0.25, 0.5)
# ball@state <- getState(ball)
# 
# state <- ball@state
# rate <- getRate(ball, state, rate)
# rate
# 
# rate <- getRate(ball, state, rate)
# rate
# 
# state <- ball@state
# rate <- getRate(ball, state, rate)
# rate
# 
# rate <- getRate(ball, state, rate)
# rate
```


```{r}
source("./R/FallingParticleODE.R")

ball <- FallingParticleODE(10, 0)
ball
```


```{r}
source("./R/ODESolver.R")
source("./R/FallingParticleODE.R")
source("./R/Euler.R")

initial_y <- 10
initial_v <- 0
dt <- 0.01
rate <- c(0,0,0)

ball <- FallingParticleODE(initial_y, initial_v)

odesolver <- ODESolver(ball)

odesolver@stepSize
odesolver <- setStepSize(odesolver, 0.01)
odesolver@stepSize

odesolver@numEqn
odesolver@ode

initSolver(odesolver, 0.02)

ball@rate
```
