---
title: "Zelle Cannonball S4 class"
output: html_notebook
---

Source: Python, and introduction to computer science. Page 309

```{r}

setClass("Projectile", slots = c(
    xpos = "numeric",
    ypos = "numeric",
    xvel = "numeric",
    yvel = "numeric"
))

setGeneric("update", function(object, time) standardGeneric("update"))
setGeneric("getY", function(object) standardGeneric("getY"))
setGeneric("getX", function(object) standardGeneric("getX"))


setMethod("initialize", "Projectile",
          function(.Object, xpos = xpos, ypos = ypos, xvel = xvel, yvel = yvel){
            .Object@xpos <- xpos
            .Object@ypos <- ypos
            .Object@xvel <- xvel
            .Object@yvel <- yvel
            return(.Object)
          })

setMethod("update", "Projectile", function(object, time) {
    object@xpos <-  object@xpos + time * object@xvel
    yvel1 <- object@yvel - 9.8 * time
    object@ypos <-  object@ypos + time * (object@yvel +  yvel1) / 2.0
    object@yvel <-  yvel1
    return(object)
})

setMethod("getY", "Projectile", function(object) {
    return(object@ypos)
})

setMethod("getX", "Projectile", function(object) {
    return(object@xpos)
})

# constructor
Projectile <- function(angle, velocity, height) {
    xpos <-  0
    ypos <-  height
    theta <- pi * angle / 180.0
    xvel <- velocity * cos(theta)
    yvel <- velocity * sin(theta)
    new("Projectile", xpos, ypos, xvel, yvel)
}
```


```{r}
interval <-  0.25
cball <- Projectile(angle = 45, velocity = 50, height = 0)
while (getY(cball) >= 0) {
    cball <- update(cball, interval)    
    cat(getX(cball), getY(cball), "\n")
}
```

