---
title: "KeplerApp"
output: html_notebook
---

## Lessons learned
* A call to generic functions in other classes causes errors when a call is made to a major class.


```{r}

source("./R/ode_generics.R")
source("./R/Kepler.R")
source("./R/RK45.R")

# set the orbit into a predefined state.
r <- c(2, 0)
v <- c(0, 0.25)
dt <- 0.1

planet <- Kepler(r, v)
solver <- RK45(planet)

# solver <- step(solver)

while (planet@state[5] <= 10) {
    solver <- step(solver)
    planet <- solver@ode
    cat(sprintf("state[1]=%12f, state[2]= %12f,  state[3]=%12f, state[5]=%12f\n", 
                planet@state[1],
                planet@state[2], planet@state[3], planet@state[5]))
}

# at t=100, dt=0.1,  c(2.131958,     1.105316,   100.000000)
# Java: state[0] = 0.444912, state[1]= -1.436203, state[2]= 0.459081, state[4]= 10.033245
#       currentStep=    0.061646
# R:    state[1] = 0.444912, state[2]= -1.436203, state[3]= 0.459081, state[5]= 10.033245 
#       currentStep= 0.06164632

```




```{r}
# ReactionApp solves an autocatalytic oscillating chemical 
# reaction (Brusselator model) using
# a fouth-order Runge-Kutta algorithm.

source("./R/ode_generics.R")
source("./R/Reaction.R")
source("./R/RK4.R")

X <- 1; Y <- 5;
dt <- 0.1

reaction <- Reaction(c(X, Y, 0))

solver <- RK4(reaction)

x11()
window = 10
while (solver@ode@state[3] < 100) {
    # flush.console()
        cat(sprintf("%12f %12f %12f \n", solver@ode@state[1], 
        solver@ode@state[2], 
        solver@ode@state[3]))
    solver <- step(solver)    
    # plot(solver@ode@state[3], solver@ode@state[1], type = "l", las = 1, ylim =c(0,3),
    #      xlim = c(solver@ode@state[3], solver@ode@state[3] + window))
    myplot <- ggplot2::qplot(solver@ode@state[3], solver@ode@state[2], 
                             geom = c("line", "smooth"), xlim = c(solver@ode@state[3], solver@ode@state[3] + window))
    Sys.sleep(.09)
    print(myplot)
}

```

